repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  # https://github.com/pre-commit/pre-commit-hooks
  hooks:
  # - id: check-yaml

  # ファイルが改行で終わり、改行のみであることを確認します。
  - id: end-of-file-fixer

  # 末尾の空白をトリムします。
  - id: trailing-whitespace

  # AWS CLI で設定した AWS シークレットの存在を確認します。
  - id: detect-aws-credentials

  # 秘密鍵の存在を確認します。
  - id: detect-private-key

  # 二重引用符で囲まれた文字列を一重引用符で囲まれた文字列に置き換えます。
  - id: double-quote-string-fixer

  # 混合行末を置換またはチェックします。
  - id: mixed-line-ending
    args: [--fix=no]

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    exclude: migrations/
    additional_dependencies: [flake8-isort]
