name: Python CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pipenv"
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev
      - name: Check security
        run: |
          pipenv check
          pipenv run ./manage.py check
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
      - name: Lint
        run: |
          pipenv run pre-commit install
          pipenv run flake8 . --count --show-source --statistics
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --relative origin/${{ github.base_ref }}... --name-only | xargs pipenv run pre-commit run --files
      - name: Test
        run: |
          pipenv run ./manage.py test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
